### PR TITLE
fix(dropdowns): Removed divider from Log out dropdown and Removed dro…

### LINKED ISSUE #200: Empty divider in Log Out dropdown and non-functional Log In button
### Description
There is an empty divider in Log Out drop down, earlier that place used to house the theme toggle. But since it was removed from the drop down in an earlier commit the divider is no longer required. Same issues plagues the Log In button in the home page. Its only functionality is it redirects the user back to the home page on being clicked but since we can't access any page other than the home page while not being logged in I think it should be removed altogether.

#### Screenshots
Current Log Out dropdown:
wrong-logout

Current Log In dropdown:
wrong_login

### Versions

* Last commit id on master: #77a85c
* Operating System (lsb_release -a): Ubuntu 20.04
* Browser [e.g. chrome, safari]: Mozilla Firefox, Chrome

### PR DESCRIPTION
**Pull request by pret3nti0u5**
…pdown on homepage

## Description

Closes #200 

### Changes

Removed <Dropdown.Divider /> from Log Out dropdown and Removed Log In dropdown since it served no functionality.

## Screenshots
right-logout

## How to test

1. yarn start.
2. Check Log In dropdown by clicking top right user icon.
3. Check Log Out dropdown by Logging In and clicking top right user icon.

### CODE REVIEW

File: src/components/Header/index.jsx [hunk 1]
```diff
@@ -58,11 +58,7 @@ const Header = () => {
   const [currentGroup, setCurrentGroup] = useState(
     getLocalStorage("currentGroup") || getLocalStorage("user")?.default_group
   );
-  const history = useHistory();
   const location = useLocation();
-  const handleLogin = () => {
-    history.push(routes.home);
-  };
```
Comment (GMishx) [inline src/components/Header/index.jsx:65]: Can you please explain the changes done here?

File: src/components/Header/index.jsx [hunk 2]
```diff
@@ -373,13 +369,9 @@ const Header = () => {
                 <Dropdown.Item onClick={() => logout(null)}>
                   Log out
                 </Dropdown.Item>
-                <Dropdown.Divider />
               </Dropdown.Menu>
             ) : (
-              <Dropdown.Menu>
-                <Dropdown.Item onClick={handleLogin}>Log in</Dropdown.Item>
-                <Dropdown.Divider />
-              </Dropdown.Menu>
```
Comment (GMishx) [inline src/components/Header/index.jsx:382]: Can you please explain the need to remove the login button?

File: src/components/Header/index.jsx (hunk 1 above)
Comment (pret3nti0u5) [reply src/components/Header/index.jsx:65]: From what I can understand, the `handleLogin()` function basically redirects users to the home page when the Log In button on the dropdown is clicked. But when the user is logged out the only page he can access is the home page, so the button serves no purpose. 

Even if it fired the same function as the Log In button on the home page it would've served some purpose but as it stands now it's redundant.

File: src/components/Header/index.jsx (hunk 2 above)
Comment (pret3nti0u5) [reply src/components/Header/index.jsx:382]: As explained above, the button is redundant. Earlier the dropdown had some purpose as the Light to Dark theme switch was located in that drop down but now it only houses a redundant button.
Replacing the `<Dropdown.Menu/>` with an empty `<div />` removes any drop down when the user is not logged in.

File: src/components/Header/index.jsx (hunk 1 above)
Comment (GMishx) [reply src/components/Header/index.jsx:65]: What if the user is not logged in and is on a different page, say one of the help page. If they want to login, drop-down provides a simpler path to do it.
What do you think?

Comment (pret3nti0u5) [reply src/components/Header/index.jsx:65]: Agreed, I failed to take that into consideration. I'll revert the changes and just remove the extra divider from the Log In dropdown. So it look like such:
right_login

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Review by GMishx — APPROVED** [review]
Tested, working as expected.
